In [39]:
import numpy as np
from IPython.display import display, HTML

## 基本属性
--------------

* ndarray (N Dimension Array)
* dtype
* shape

In [40]:
arr = np.arange(10).reshape(2,5)
display(arr)
print('dtype: ',arr.dtype)
print('shape: ', arr.shape)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

dtype:  int64
shape:  (2, 5)


## [创建](https://numpy.org/doc/stable/reference/routines.array-creation.html#)
----------------
* 通过现有数据创建
* 通过现有shape or value
* 通过range
* random
* reshape (1维 -> n维)

In [42]:
# 1. 通过现有数据创建
arr1 = np.array([1,2,3,4,5,6])
display(arr1)

arr2 = np.asarray([1,2,3,4,5,6]).reshape(2,3)
display(arr2)

# 2. 通过现有shape or value
arr3 = np.zeros(2,5)
arr3_1 = np.zeros_like(arr1)

arr4 = np.ones(2,5)
arr4_1 = np.ones_like(arr1)

arr5 = np.empty(2,5)
arr5_1 = np.empty_like(arr1)



# 3. 通过range
arr6 = np.arange(10, 20, 2)

# 4. random
arr7 = np.random.random(10)
arr8 = np.random.randn(2,3)

# 5. 1维 -》 N维
arr9 = np.random.randn(10).reshape(2,5)



array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])