In [4]:
import numpy as np
from IPython.display import display, HTML

## 1. 基本属性
--------------

* ndarray (N Dimension Array)
* dtype
* shape

In [44]:
arr1 = np.arange(10).reshape(2,5)
display(arr1)
print('dtype: ',arr1.dtype)
print('shape: ', arr1.shape)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

dtype:  int64
shape:  (2, 5)


## 2. [创建](https://numpy.org/doc/stable/reference/routines.array-creation.html#)
----------------
* 通过现有数据创建
* 通过现有shape or value
* 通过range
* random
* reshape (1维 -> n维)

In [48]:
# 2.1 通过现有数据创建
arr1 = np.array([1,2,3,4,5,6])

arr2 = np.asarray([1,2,3,4,5,6]).reshape(2,3)


# 2.2 通过现有shape or value
arr221 = np.zeros((2,5))
arr221_1 = np.zeros_like(arr1)

arr222 = np.ones((2,5))
arr222_1 = np.ones_like(arr1)

arr223 = np.empty((2,5))
arr223_1 = np.empty_like(arr1)


# 2.3 通过range
arr23 = np.arange(10, 20, 2)


# 2.4 random
arr24 = np.random.random(10)
arr24_2 = np.random.randn(2,3)


# 2.5 1维 -》 N维
arr25 = np.random.randn(10).reshape(2,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 3. 访问
* 基础索引及切片
* 布尔索引
* 神奇索引

In [102]:

# 3.1 基础索引
arr3 = np.arange(30).reshape(6,5)
display(arr3)

# 3.1.1 单个元素 = 单列 + 单行
arr3131 = arr3[2,1] # 第2行第1列

# 3.1.2 单行 = 单行 + 多个列
arr312 = arr3[1, :] # 所有列
arr312_1 = arr3[1, [1,3]] #多列支持
arr312_2 = arr3[1, 1:3] #连续的多列

# 3.1.3 单列 = 单列 + 多个行
arr313 = arr3[:, 1] #多列支持
arr313_1 = arr3[[1,3], 1] #多列支持
arr313_2 = arr3[1:3, 1] #连续的多行

# 3.1.4 子数组 = 多行 + 多列
arr314 = arr3[:, :]
arr314_1 = arr3[[1,3], 1:3]


# 3.2 布尔索引
# 3.2.1 一维布尔索引
arr321 = np.arange(30).reshape(6,5)
arr321_names = np.array(['Joe', 'Bob', 'Bob', 'Allen', 'Bob', 'Joe'])
# arr321_bool = (arr321_names == 'Joe') # 一维布尔值
arr321[arr321_names == 'Joe'] = 0  # 第一行和最后一行被选中赋值了
arr321_2 = np.arange(30).reshape(6,5)
arr321_2[~(arr321_names == 'Joe')] = 0  # 除了第一和最后一行被选中赋值了


# 3.2.2 二维布尔索引
arr322 = np.arange(30).reshape(6,5)
arr322[arr322%5 ==0] = 0 # 所有被5整除的数置为0

# 3.3 神奇索引 （整数数组索引）
# 生成了一个新的数组
arr33 = np.arange(30).reshape(6,5)
# array([[ 0,  1,  2,  3,  4],
#        [ 5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14],
#        [15, 16, 17, 18, 19],
#        [20, 21, 22, 23, 24],
#        [25, 26, 27, 28, 29]])

# 3.3.1 一维数组

arr331 = arr33[[3,1]] #选中第三和第一行
# array([[15, 16, 17, 18, 19],
#        [ 5,  6,  7,  8,  9]])

# 3.3.2 二维数组
arr332 = arr33[[3,1],[1,2]]
# 违反直觉！！！
# 结果是一维数组元素(3,1), (1,2)
# array([16,  7])

# 这才是想要的，需要每次选一维，先选行，然后先列
arr332_1 = arr33[[3,1]][:, [1,2]]
#array([[16, 17],
#       [ 6,  7]])


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

array([[16, 17],
       [ 6,  7]])

## 4. 运算
* [数学计算](https://numpy.org/doc/stable/reference/routines.math.html)
* 统计计算
* 排序
* 线性代数

In [23]:
# 4.1 数学计算
arr41 = np.arange(30).reshape(6,5)
arr41_2 = np.arange(1,6)
arr41_3 = np.arange(60,90).reshape(6,5)

# 4.1.1 基础运算
# 逐个元素计算
# 2维与标量计算 [[1,2],[3,4]] * 2 = [[1,2]*2, [3,4] * 2] = [[1*2, 2*2], [3*2, 4*2]]

# 4.1.1.1 2维 + 0维
arr4111_1 = arr41 + 2
arr4111_2 = arr41 - 2
arr4111_3 = arr41 * 2
arr4111_4 = arr41 / 2
arr4111_5 = arr41 ** 2
arr4111_6 = arr41 % 2
arr4111_7 = arr41 > 2

# 4.1.1.2 2维 + 1维
arr4112_1 = arr41 + arr41_2
arr4112_2 = arr41 - arr41_2
arr4112_3 = arr41 * arr41_2
arr4112_4 = arr41 / arr41_2

# 4.1.1.3 2维 + 2维
arr4113_1 = arr41 + arr41_3
arr4113_2 = arr41 - arr41_3
arr4113_3 = arr41 * arr41_3
arr4113_4 = arr41 / arr41_3

# 4.1.2 通用函数
#array([[ 0,  1,  2,  3,  4],
#       [ 5,  6,  7,  8,  9],
#       [10, 11, 12, 13, 14],
#       [15, 16, 17, 18, 19],
#       [20, 21, 22, 23, 24],
#       [25, 26, 27, 28, 29]])

arr412_1 = np.sum(arr41)
arr412_2 = np.sum(arr41, axis=1)
arr412_3 = np.sum(arr41, axis=0)
