In [ ]:
import numpy as np
from IPython.display import display, HTML

# 基本属性
--------------

* ndarray (N Dimension Array)
* dtype
* shape

In [ ]:
arr1 = np.arange(10).reshape(2, 5)
display(arr1)
print('dtype: ', arr1.dtype)
print('shape: ', arr1.shape)


# [创建](https://numpy.org/doc/stable/reference/routines.array-creation.html#)
----------------

## 通过现有数据创建

In [ ]:
arr21_1 = np.array([1, 2, 3, 4, 5, 6])
arr21_2 = np.asarray([1, 2, 3, 4, 5, 6]).reshape(2, 3)

## 通过现有shape或者value

In [ ]:
arr22_1 = np.array([1, 2, 3, 4, 5, 6])
arr22_2 = np.asarray([1, 2, 3, 4, 5, 6]).reshape(2, 3)

arr221_1 = np.zeros((2, 5))
arr221_2 = np.zeros_like(arr1)

arr222_1 = np.ones((2, 5))
arr222_2 = np.ones_like(arr1)

arr223_1 = np.empty((2, 5))
arr223_2 = np.empty_like(arr1)

## 通过range创建

In [ ]:
arr23 = np.arange(10, 20, 2)

## random创建

In [ ]:
arr24 = np.random.random(10)
arr24_2 = np.random.randn(2, 3)

## reshape
先创建1维 -> N维

In [ ]:
arr25 = np.random.randn(10).reshape(2, 5)

# 访问
-----------------------


## 基础索引及切片

In [ ]:
arr3 = np.arange(30).reshape(6, 5)
display(arr3)

# 3.1.1 单个元素 = 单列 + 单行
arr3131 = arr3[2, 1]  # 第2行第1列

# 3.1.2 单行 = 单行 + 多个列
arr312 = arr3[1, :]  # 所有列
arr312_1 = arr3[1, [1, 3]]  #多列支持
arr312_2 = arr3[1, 1:3]  #连续的多列

# 3.1.3 单列 = 单列 + 多个行
arr313 = arr3[:, 1]  #多列支持
arr313_1 = arr3[[1, 3], 1]  #多列支持
arr313_2 = arr3[1:3, 1]  #连续的多行

# 3.1.4 子数组 = 多行 + 多列
arr314 = arr3[:, :]
arr314_1 = arr3[[1, 3], 1:3]

## 布尔索引

In [ ]:
# 3.2.1 一维布尔索引
arr321 = np.arange(30).reshape(6, 5)
arr321_names = np.array(['Joe', 'Bob', 'Bob', 'Allen', 'Bob', 'Joe'])
# arr321_bool = (arr321_names == 'Joe') # 一维布尔值
arr321[arr321_names == 'Joe'] = 0  # 第一行和最后一行被选中赋值了
arr321_2 = np.arange(30).reshape(6, 5)
arr321_2[~(arr321_names == 'Joe')] = 0  # 除了第一和最后一行被选中赋值了

# 3.2.2 二维布尔索引
arr322 = np.arange(30).reshape(6, 5)
arr322[arr322 % 5 == 0] = 0  # 所有被5整除的数置为0

## 神奇索引 （整数数组索引）
整数索引会产生新的数组！！！

In [ ]:
arr33 = np.arange(30).reshape(6, 5)
# array([[ 0,  1,  2,  3,  4],
#        [ 5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14],
#        [15, 16, 17, 18, 19],
#        [20, 21, 22, 23, 24],
#        [25, 26, 27, 28, 29]])

# 3.3.1 一维数组

arr331 = arr33[[3, 1]]  #选中第三和第一行
# array([[15, 16, 17, 18, 19],
#        [ 5,  6,  7,  8,  9]])

# 3.3.2 二维数组
arr332 = arr33[[3, 1], [1, 2]]
# 违反直觉！！！
# 结果是一维数组元素(3,1), (1,2)
# array([16,  7])

# 这才是想要的，需要每次选一维，先选行，然后先列
arr332_1 = arr33[[3, 1]][:, [1, 2]]
#array([[16, 17],
#       [ 6,  7]])


# 运算

## [数学计算](https://numpy.org/doc/stable/reference/routines.math.html)

In [ ]:
arr41 = np.arange(30).reshape(6, 5)
arr41_2 = np.arange(1, 6)
arr41_3 = np.arange(60, 90).reshape(6, 5)

### 基础运算

In [ ]:
# 逐个元素计算(broadcast)
# 2维与标量计算 [[1,2],[3,4]] * 2 = [[1,2]*2, [3,4] * 2] = [[1*2, 2*2], [3*2, 4*2]]

# 4.1.1.1 2维 + 0维
arr4111_1 = arr41 + 2
arr4111_2 = arr41 - 2
arr4111_3 = arr41 * 2
arr4111_4 = arr41 / 2
arr4111_5 = arr41 ** 2
arr4111_6 = arr41 % 2
arr4111_7 = arr41 > 2

# 4.1.1.2 2维 + 1维
arr4112_1 = arr41 + arr41_2
arr4112_2 = arr41 - arr41_2
arr4112_3 = arr41 * arr41_2
arr4112_4 = arr41 / arr41_2

# 4.1.1.3 2维 + 2维
arr4113_1 = arr41 + arr41_3
arr4113_2 = arr41 - arr41_3
arr4113_3 = arr41 * arr41_3
arr4113_4 = arr41 / arr41_3

### 通用函数计算

In [ ]:
#array([[ 0,  1,  2,  3,  4],
#       [ 5,  6,  7,  8,  9],
#       [10, 11, 12, 13, 14],
#       [15, 16, 17, 18, 19],
#       [20, 21, 22, 23, 24],
#       [25, 26, 27, 28, 29]])
arr412 = np.arange(30).reshape(6, 5)
arr412_2 = np.arange(30, 60).reshape(6, 5)

# 4.1.2.1 一维函数
arr4121_1 = np.sqrt(arr412)
arr4121_2 = np.abs(arr412)
arr4121_3 = np.square(arr412)

# 4.1.2.2 二维函数
arr4122_1 = np.add(arr412, arr412_2)
arr4122_2 = np.maximum(arr412, arr412_2)

# 4.1.2.3 三元函数
arr4123_1 = np.where(arr412 > 10, 0, 1)


## 统计计算

### 常用统计计算

In [ ]:
arr421 = np.arange(30).reshape(6, 5)
arr421_1 = np.sum(arr421)  #聚合成0维
arr421_2 = np.mean(arr421)
arr421_3 = np.min(arr421)
arr421_4 = np.max(arr421)
arr421_5 = np.cumsum(arr421)
arr421_6 = np.cumprod(arr421)
arr421_7 = np.argmin(arr421)
arr421_8 = np.argmax(arr421)

### 轴向统计计算

In [11]:
arr422 = np.arange(30).reshape(6, 5)
# array([[ 0,  1,  2,  3,  4],
#        [ 5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14],
#        [15, 16, 17, 18, 19],
#        [20, 21, 22, 23, 24],
#        [25, 26, 27, 28, 29]])
arr422_1 = np.sum(arr422, axis=0)  # 聚合成一维
arr422_2 = np.mean(arr422, axis=1)  #聚合成一维
arr422_3 = np.cumsum(arr422, axis=0)  #不降维
arr422_4 = np.cumprod(arr422, axis=1)  #不降维

arr422_1

array([75, 81, 87, 93, 99])

## 排序
-----------------

In [ ]:
arr43 = np.arange(30, 0, -1).reshape(6, 5)
# arr43
arr43.sort()  # in place
arr43_2 = np.sort(arr43, axis=1)  # 会产生新的arr


## 集合逻辑
----------------

In [ ]:
arr44_1 = np.array([1, 2, 2, 3, 4, 5])
arr44_2 = np.array([4, 5, 6, 5])

arr44_3 = np.unique(arr44_1)  #计算唯一值
arr44_4 = np.intersect1d(arr44_1, arr44_2)  #计算交集
arr44_5 = np.union1d(arr44_1, arr44_2)  #计算交集
arr44_6 = np.in1d(arr44_1, arr44_2)  #x是否是y的子集
arr44_7 = np.setdiff1d(arr44_1, arr44_2)  #差集
arr44_8 = np.setxor1d(arr44_1, arr44_2)  #异或集

## [线性代数](https://numpy.org/doc/stable/reference/routines.linalg.html)
-------------

In [ ]:
arr45 = np.arange(30, 0, -1).reshape(6, 5)
arr45_1 = arr45.T  # 矩阵转置
np.dot(arr45, arr45.T)  #点乘

## 其他
-----------

### 布尔值数组逻辑

In [ ]:
arr461 = np.array([[True, False, False, False], [False, False, False, False]])
arr461_1 = arr461.any()
arr461_2 = arr461.all()
